

  .oooooo.    ooooooooo.   ooooooooooooo  .oooooo..o                                 
 d8P'  `Y8b   `888   `Y88. 8'   888   `8 d8P'    `Y8                                 
888            888   .d88'      888      Y88bo.       .ooooo.   .oooo.   ooo. .oo.   
888            888ooo88P'       888       `"Y8888o.  d88' `"Y8 `P  )88b  `888P"Y88b  
888     ooooo  888              888           `"Y88b 888        .oP"888   888   888  
`88.    .88'   888              888      oo     .d8P 888   .o8 d8(  888   888   888  
 `Y8bood8P'   o888o            o888o     8""88888P'  `Y8bod8P' `Y888""8o o888o o888o                                                        


                                                                   

[18:12:14] Loaded 10 rules                                                                                                                                                                             tasks.py:119
           Traceback (most recent call last):                                                                                                                                                          tasks.py:126
             File "/home/owen/Documents/GitHub/GPTScan-Bigger-Model/src/tasks.py", line 124, in simple_cli                                                                                                         
               falcon_instance = compile_project(source_dir)                                                                                                                                                       
             File "/home/owen/Documents/GitHub/GPTScan-Bigger-Model/src/tasks.py", line 103, in compile_project                                                                                                    
               return falcon.Falcon(abs_path)                                                                                                                                                                      
             File "/home/owen/Documents/GitHub/GPTScan-Bigger-Model/.venv/lib/python3.10/site-packages/falcon/falcon.py", line 90, in __init__                                                                     
               crytic_compile = CryticCompile(target, **kwargs)                                                                                                                                                    
             File "/home/owen/Documents/GitHub/GPTScan-Bigger-Model/.venv/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 117, in __init__                                                    
               platform = self._init_platform(target, **kwargs)                                                                                                                                                    
             File "/home/owen/Documents/GitHub/GPTScan-Bigger-Model/.venv/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 531, in _init_platform                                              
               platform = next(                                                                                                                                                                                    
             File "/home/owen/Documents/GitHub/GPTScan-Bigger-Model/.venv/lib/python3.10/site-packages/crytic_compile/crytic_compile.py", line 532, in <genexpr>                                                   
               (p(target) for p in platforms if p.is_supported(target, **kwargs)), None                                                                                                                            
             File "/home/owen/Documents/GitHub/GPTScan-Bigger-Model/.venv/lib/python3.10/site-packages/crytic_compile/platform/waffle.py", line 255, in is_supported                                               
               package = json.load(file_desc)                                                                                                                                                                      
             File "/usr/lib/python3.10/json/__init__.py", line 293, in load                                                                                                                                        
               return loads(fp.read(),                                                                                                                                                                             
             File "/usr/lib/python3.10/json/__init__.py", line 346, in loads                                                                                                                                       
               return _default_decoder.decode(s)                                                                                                                                                                   
             File "/usr/lib/python3.10/json/decoder.py", line 337, in decode                                                                                                                                       
               obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                                                                                                                   
             File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode                                                                                                                                   
               raise JSONDecodeError("Expecting value", s, err.value) from None                                                                                                                                    
           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)                                                                                                                                 
                                                                                                                                                                                                                   
           Compile failed.                                                                                                                                                                             tasks.py:127
           Since the compilation is failed, some static analysis tool may not be enabled, which may cause lower precision and recall.                                                                  tasks.py:128
                      Scan Results                       
┏━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Type ┃ Description ┃ Affected Files ┃ Analysis Report ┃
┡━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
└──────┴─────────────┴────────────────┴─────────────────┘
                   Summary                   
┏━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━┓
┃ Key                  ┃ Value              ┃
┡━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━┩
│ Files                │ 0                  │
│ Contracts            │ 0                  │
│ Functions            │ 0                  │
│ Lines of Code        │ 0                  │
│ Used Time            │ 0.7366015911102295 │
│ Estimated Cost (USD) │ 0.0                │
└──────────────────────┴────────────────────┘
